services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: derma
      POSTGRES_PASSWORD: derma
      POSTGRES_DB: derma
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  ai-service:
    build: 
      context: .
      dockerfile: ./ai-service/Dockerfile
    env_file:
      - ./ai-service/.env
    ports:
      - "8001:8001"
    depends_on:
      - postgres

  backend-api:
    build: ./backend-api
    env_file:
      - ./backend-api/.env
    environment:
      - DATABASE_URL=postgresql+psycopg://derma:derma@postgres:5432/derma
      - AI_SERVICE_URL=http://ai-service:8001
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - ai-service

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend-api

volumes:
  pg_data:
