[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gppm-backend-api"
version = "0.0.0"
description = "Backend API for GPPM (local editable package)"
authors = [{name = "GPPM"}]

[tool.setuptools.packages.find]
where = ["."]
