name: E2E - Frontend to Backend
on:
  push:
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build and start stack
        run: echo "E2E tests temporarily disabled - requires full docker setup"

      - name: Skip tests
        run: echo "Skipping E2E tests - not configured yet"
