name: E2E - Frontend to Backend
on:
  push:
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build and start stack
        run: |
          docker compose up -d --build
          # wait for services
          until curl -fsS http://localhost:3000 >/dev/null; do echo "waiting frontend"; sleep 2; done
          until curl -fsS http://localhost:8000/health >/dev/null; do echo "waiting backend"; sleep 2; done
          until curl -fsS http://localhost:8001/health >/dev/null; do echo "waiting ai-service"; sleep 2; done

      - name: Install Playwright deps
        working-directory: frontend
        run: |
          npm ci || npm install
          npx playwright install --with-deps

      - name: Run E2E tests
        working-directory: frontend
        run: npm run test:e2e

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright-report
